# Generated by Django 3.1.2 on 2020-10-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201003_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
